site_name: Init Pixel Blender Addons
site_url: https://example.com/
nav:
    # - Home: index.md
    - Spritehandler:
        - Overview: Spritehandler/overview.md
        - UI Content: Spritehandler/ui_contents.md
        - Sheet Use: Spritehandler/sheet_usage.md
        - Sheet Creation: Spritehandler/sheet_creation.md
        - Legacy Docs: Spritehandler/legacy.md
    - Node Switcher:
        - Overview: Node_Switcher/overview.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - md_in_html
